// <auto-generated />
using System;
using MailEngine.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MailEngine.Infrastructure.Migrations
{
    [DbContext(typeof(MailEngineDbContext))]
    [Migration("20260204233403_shyte_fest_x3")]
    partial class shyte_fest_x3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailEngine.Core.Models.FailedMessage", b =>
                {
                    b.Property<Guid>("FailedMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("failed_message_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorMessageTxt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_message_txt");

                    b.Property<string>("ErrorStackTraceTxt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_stack_trace_txt");

                    b.Property<DateTime>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<string>("MessageContentTxt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_content_txt");

                    b.Property<string>("MessageIdTxt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_id_txt");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<int>("RetryCountNo")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count_no");

                    b.Property<string>("StatusCd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_cd");

                    b.Property<string>("SubscriptionTxt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscription_txt");

                    b.Property<string>("TopicCd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic_cd");

                    b.HasKey("FailedMessageId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("idx_failed_messages_created_at_utc");

                    b.HasIndex("StatusCd")
                        .HasDatabaseName("idx_failed_messages_status_cd");

                    b.HasIndex("TopicCd")
                        .HasDatabaseName("idx_failed_messages_topic_cd");

                    b.ToTable("failed_messages", "public");
                });

            modelBuilder.Entity("MailEngine.Core.Models.OAuthToken", b =>
                {
                    b.Property<Guid>("OAuthTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("oauth_token_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessTokenTxt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token_txt");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("RefreshTokenTxt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_txt");

                    b.Property<Guid>("UserMailAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_mail_account_id");

                    b.HasKey("OAuthTokenId");

                    b.ToTable("oauth_tokens", "public");
                });

            modelBuilder.Entity("MailEngine.Core.Models.ProcessedMessage", b =>
                {
                    b.Property<Guid>("ProcessedMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("processed_message_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("ProcessedMessageId");

                    b.HasIndex("EventType")
                        .HasDatabaseName("idx_processed_messages_event_type");

                    b.HasIndex("IdempotencyKey")
                        .HasDatabaseName("idx_processed_messages_idempotency_key");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("idx_processed_messages_message_id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("idx_processed_messages_processed_at");

                    b.ToTable("processed_messages", "public");
                });

            modelBuilder.Entity("MailEngine.Core.Models.UserMailAccount", b =>
                {
                    b.Property<Guid>("UserMailAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_mail_account_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EmailAddressTxt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_address_txt");

                    b.Property<bool>("IsActiveFalg")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active_flg");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<int>("ProviderCd")
                        .HasColumnType("integer")
                        .HasColumnName("provider_cd");

                    b.HasKey("UserMailAccountId");

                    b.ToTable("user_mail_accounts", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
