CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260202162456_InitialCreateWithNamingConventions') THEN
    CREATE TABLE public.failed_messages (
        failed_message_id uuid NOT NULL,
        message_id_txt text NOT NULL,
        topic_cd text NOT NULL,
        subscription_txt text NOT NULL,
        error_message_txt text NOT NULL,
        error_stack_trace_txt text NOT NULL,
        failed_at_utc timestamp with time zone NOT NULL,
        status_cd text NOT NULL,
        retry_count_no integer NOT NULL,
        resolved_at_utc timestamp with time zone,
        message_content_txt text NOT NULL,
        created_at_utc timestamp with time zone NOT NULL,
        modified_at_utc timestamp with time zone NOT NULL,
        CONSTRAINT "PK_failed_messages" PRIMARY KEY (failed_message_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260202162456_InitialCreateWithNamingConventions') THEN
    CREATE TABLE public.oauth_tokens (
        oauth_token_id uuid NOT NULL,
        user_mail_account_id uuid NOT NULL,
        access_token_txt text NOT NULL,
        refresh_token_txt text NOT NULL,
        expires_at_utc timestamp with time zone NOT NULL,
        created_at_utc timestamp with time zone NOT NULL,
        modified_at_utc timestamp with time zone NOT NULL,
        CONSTRAINT "PK_oauth_tokens" PRIMARY KEY (oauth_token_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260202162456_InitialCreateWithNamingConventions') THEN
    CREATE TABLE public.user_mail_accounts (
        user_mail_account_id uuid NOT NULL,
        email_address_txt text NOT NULL,
        provider_cd integer NOT NULL,
        is_active_flg boolean NOT NULL,
        created_at_utc timestamp with time zone NOT NULL,
        modified_at_utc timestamp with time zone NOT NULL,
        CONSTRAINT "PK_user_mail_accounts" PRIMARY KEY (user_mail_account_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260202162456_InitialCreateWithNamingConventions') THEN
    CREATE INDEX idx_failed_messages_created_at_utc ON public.failed_messages (created_at_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260202162456_InitialCreateWithNamingConventions') THEN
    CREATE INDEX idx_failed_messages_status_cd ON public.failed_messages (status_cd);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260202162456_InitialCreateWithNamingConventions') THEN
    CREATE INDEX idx_failed_messages_topic_cd ON public.failed_messages (topic_cd);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260202162456_InitialCreateWithNamingConventions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260202162456_InitialCreateWithNamingConventions', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260202190330_AddAutoGeneratedGuidsForPrimaryKeys') THEN
    ALTER TABLE public.user_mail_accounts ALTER COLUMN user_mail_account_id SET DEFAULT (gen_random_uuid());
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260202190330_AddAutoGeneratedGuidsForPrimaryKeys') THEN
    ALTER TABLE public.oauth_tokens ALTER COLUMN oauth_token_id SET DEFAULT (gen_random_uuid());
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260202190330_AddAutoGeneratedGuidsForPrimaryKeys') THEN
    ALTER TABLE public.failed_messages ALTER COLUMN failed_message_id SET DEFAULT (gen_random_uuid());
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260202190330_AddAutoGeneratedGuidsForPrimaryKeys') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260202190330_AddAutoGeneratedGuidsForPrimaryKeys', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260204213713_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260204213713_InitialCreate', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260204225348_Tables_Again') THEN
    CREATE TABLE public.processed_messages (
        processed_message_id uuid NOT NULL DEFAULT (gen_random_uuid()),
        message_id text NOT NULL,
        idempotency_key text,
        event_type text NOT NULL,
        processed_at timestamp with time zone NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_processed_messages" PRIMARY KEY (processed_message_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260204225348_Tables_Again') THEN
    CREATE INDEX idx_processed_messages_event_type ON public.processed_messages (event_type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260204225348_Tables_Again') THEN
    CREATE INDEX idx_processed_messages_idempotency_key ON public.processed_messages (idempotency_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260204225348_Tables_Again') THEN
    CREATE INDEX idx_processed_messages_message_id ON public.processed_messages (message_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260204225348_Tables_Again') THEN
    CREATE INDEX idx_processed_messages_processed_at ON public.processed_messages (processed_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260204225348_Tables_Again') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260204225348_Tables_Again', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260204225910_Tables_Againx2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260204225910_Tables_Againx2', '8.0.0');
    END IF;
END $EF$;
COMMIT;

